package ru.aasmc.wordify.common.core.cache.dao

import android.content.Context
import androidx.arch.core.executor.testing.InstantTaskExecutorRule
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.single
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import ru.aasmc.wordify.common.core.data.cache.WordifyDatabase
import ru.aasmc.wordify.common.core.data.cache.dao.WordDao
import ru.aasmc.wordify.common.core.fakes.AndroidFakeCachedWordFactory

@RunWith(AndroidJUnit4::class)
@ExperimentalCoroutinesApi
class WordDaoTest {
    private lateinit var wordifyDatabase: WordifyDatabase
    private lateinit var wordDao: WordDao

    /**
     * Swaps the background executor used by Architecture Components with the one
     * that is synchronous. It allows Room to execute all its operations instantly.
     */
    @get:Rule
    var instantTaskExecutorRule = InstantTaskExecutorRule()

    @Before
    fun setupDatabase() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        wordifyDatabase = Room.inMemoryDatabaseBuilder(
            context,
            WordifyDatabase::class.java
        )
            .build()
        wordDao = wordifyDatabase.wordDao()
    }

    @After
    fun closeDatabase() {
        wordifyDatabase.close()
    }

    @Test
    fun insertCachedWordAggregate_getByWordId_correct() = runTest {
        // given
        val cachedWord = AndroidFakeCachedWordFactory.createCachedWord(1)
        // when
        wordDao.insertCachedWordAggregate(cachedWord)
        val retrieved = wordDao.getWordById(cachedWord.cachedWord.wordId)

        // then

        // ids of some of the returned word properties would be autogenerated, so checking for
        // equality fails.
        assertEquals(cachedWord.cachedWord.wordId, retrieved?.cachedWord?.wordId)
        assertEquals(cachedWord.cachedWord.pronunciation, retrieved?.cachedWord?.pronunciation)
        assertEquals(cachedWord.cachedWord.frequency, retrieved?.cachedWord?.frequency)
        assertEquals(cachedWord.cachedWord.syllable, retrieved?.cachedWord?.syllable)
        val expectedProps = cachedWord.wordProperties[0]
        val retrievedProps = retrieved?.wordProperties?.get(0)
            ?: throw Exception("Retrieved props in test " +
                    "'insertCachedWordAggregate_getByWordId_correct' should not be null")

        assertEquals(expectedProps.derivations.size, retrievedProps.derivations.size)
        assertEquals(
            expectedProps.derivations[0].derivation,
            retrievedProps.derivations[0].derivation
        )
        assertEquals(
            expectedProps.derivations[0].propertiesId,
            retrievedProps.derivations[0].propertiesId
        )

        assertEquals(expectedProps.examples.size, retrievedProps.examples.size)
        assertEquals(expectedProps.examples[0].example, retrievedProps.examples[0].example)
        assertEquals(
            expectedProps.examples[0].propertiesId,
            retrievedProps.derivations[0].propertiesId
        )

        assertEquals(expectedProps.synonyms.size, retrievedProps.synonyms.size)
        assertEquals(expectedProps.synonyms[0].synonym, retrievedProps.synonyms[0].synonym)
        assertEquals(
            expectedProps.synonyms[0].propertiesId,
            retrievedProps.synonyms[0].propertiesId
        )

        assertEquals(
            expectedProps.cachedWordProperties.wordId,
            retrievedProps.cachedWordProperties.wordId
        )
        assertEquals(
            expectedProps.cachedWordProperties.definition,
            retrievedProps.cachedWordProperties.definition
        )
        assertEquals(
            expectedProps.cachedWordProperties.partOfSpeech,
            retrievedProps.cachedWordProperties.partOfSpeech
        )
    }

    @Test
    fun getAllWords_correctly_returns_flowWithListOf_10_Words_after_inserting_10_Words() = runTest {
        // given
        (1..10).forEach { wordId ->
            wordDao.insertCachedWordAggregate(AndroidFakeCachedWordFactory.createCachedWord(wordId))
        }
        // when
        val words = wordDao.getAllWords().take(1).single()

        // then
        assertEquals(10, words.size)
    }

    @Test
    fun searchWordByName_returns_3_words_sorted_by_name_with_similar_names() = runTest {
        // given
        wordDao.insertCachedWordAggregate(AndroidFakeCachedWordFactory.createCachedWord(1))
        wordDao.insertCachedWordAggregate(AndroidFakeCachedWordFactory.createCachedWord(11))
        wordDao.insertCachedWordAggregate(AndroidFakeCachedWordFactory.createCachedWord(111))

        // when
        val words = wordDao.searchWordsByName("1").take(1).single() ?: emptyList()

        // then
        assertEquals(3, words.size)
        assertEquals("1", words[0].cachedWord.wordId)
        assertEquals("11", words[1].cachedWord.wordId)
        assertEquals("111", words[2].cachedWord.wordId)
    }

    @Test
    fun getAllWords_returns_alphabetically_sorted_list() = runTest {
        // given
        (1..10).forEach {
            wordDao.insertCachedWordAggregate(AndroidFakeCachedWordFactory.createCachedWord(it))
        }
        // when
        val words = wordDao.getAllWords().take(1).single()
        for (i in 0 until words.lastIndex) {
            assertTrue(words[i].cachedWord.wordId <= words[i + 1].cachedWord.wordId)
        }
    }

    @Test
    fun getWordById_returns_null_if_no_word_with_name_inDb() = runTest {
        // given
        val wordToSearch = "word"
        wordDao.insertCachedWordAggregate(AndroidFakeCachedWordFactory.createCachedWord(1))
        // when
        val word = wordDao.getWordById(wordToSearch)
        // then
        assertNull(word)
    }

    @Test
    fun searchWordsByName_returns_emptyList_if_DB_has_no_words_with_that_name() = runTest {
        // given
        wordDao.insertCachedWordAggregate(AndroidFakeCachedWordFactory.createCachedWord(1))
        // when
        val words = wordDao.searchWordsByName("2").take(1).single()
        // then
        assertTrue(words.isEmpty())
    }
}


































