package ru.aasmc.wordify.resources.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF006d3a)
val light_onPrimary = Color(0xFFffffff)
val light_primaryVariant = Color(0xFF004112)
val light_secondary = Color(0xFF4f6353)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryVariant = Color(0xFF439c65)
val light_error = Color(0xFFba1b1b)
val light_onError = Color(0xFFffffff)
val light_background = Color(0xFFfbfdf7)
val light_onBackground = Color(0xFF1a1c1a)
val light_surface = Color(0xFFfbfdf7)
val light_onSurface = Color(0xFF1a1c1a)
val light_inverseOnSurface = Color(0xFFf0f1ec)
val light_inverseSurface = Color(0xFF2e312e)
val light_secondaryContainer = Color(0xFFd1e8d4)
val light_onSecondaryContainer = Color(0xFF0d1f13)
val light_tertiary = Color(0xFF3a646f)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFbeeaf7)
val light_onTertiaryContainer = Color(0xFF001f26)
val light_surfaceVariant = Color(0xFFdce5db)
val light_onSurfaceVariant = Color(0xFF414942)
val light_outline = Color(0xFF717971)
val light_onErrorContainer = Color(0xFF410001)
val light_primaryContainer = Color(0xFF51ffa2)
val light_onPrimaryContainer = Color(0xFF00210d)
val light_errorContainer = Color(0xFFffdad4)


val dark_primary = Color(0xFF00e381)
val dark_primaryVariant = Color(0xFF00b053)
val dark_onPrimary = Color(0xFF00391b)
val dark_secondary = Color(0xFFb6ccb9)
val dark_secondaryVariant = Color(0xFF65ffb1)
val dark_onSecondary = Color(0xFF223427)
val dark_error = Color(0xFFffb4a9)
val dark_onError = Color(0xFF680003)
val dark_background = Color(0xFF1a1c1a)
val dark_onBackground = Color(0xFFe1e3de)
val dark_surface = Color(0xFF1a1c1a)
val dark_onSurface = Color(0xFFe1e3de)
val dark_surfaceVariant = Color(0xFF414942)
val dark_onSurfaceVariant = Color(0xFFc0c9bf)
val dark_outline = Color(0xFF8a938a)
val dark_inverseOnSurface = Color(0xFF1a1c1a)
val dark_inverseSurface = Color(0xFFe1e3de)
val dark_primaryContainer = Color(0xFF00522a)
val dark_onPrimaryContainer = Color(0xFF51ffa2)
val dark_secondaryContainer = Color(0xFF374b3c)
val dark_onSecondaryContainer = Color(0xFFd1e8d4)
val dark_tertiary = Color(0xFFa2cdda)
val dark_onTertiary = Color(0xFF033640)
val dark_tertiaryContainer = Color(0xFF214c57)
val dark_onTertiaryContainer = Color(0xFFbeeaf7)
val dark_errorContainer = Color(0xFF930006)
val dark_onErrorContainer = Color(0xFFffdad4)

val color_Transcription = Color(0xFFc8cac4)

